FROM openjdk<version>-alpine<version>

COPY ./pom.xml ./pom.xml

COPY ./src ./src

RUN mvn dependency:go-offline -B

# RUN mvn package


WORKDIR /SITE

# COPY --from=maven target/SimpleJavaProject-*.jar ./SimpleJavaProject.jar

# CMD ["java", "-jar", "./SimpleJavaProject.jar"]
